# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\auth_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_auth_login(object):
    def setupUi(self, auth_login):
        auth_login.setObjectName("auth_login")
        auth_login.resize(416, 259)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(auth_login.sizePolicy().hasHeightForWidth())
        auth_login.setSizePolicy(sizePolicy)
        auth_login.setMinimumSize(QtCore.QSize(416, 259))
        auth_login.setMaximumSize(QtCore.QSize(416, 259))
        self.from_input = QtWidgets.QWidget(auth_login)
        self.from_input.setGeometry(QtCore.QRect(50, 60, 301, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.from_input.sizePolicy().hasHeightForWidth())
        self.from_input.setSizePolicy(sizePolicy)
        self.from_input.setMinimumSize(QtCore.QSize(301, 140))
        self.from_input.setMaximumSize(QtCore.QSize(301, 141))
        self.from_input.setSizeIncrement(QtCore.QSize(301, 141))
        self.from_input.setBaseSize(QtCore.QSize(301, 141))
        self.from_input.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.from_input.setObjectName("from_input")
        self.gridLayout = QtWidgets.QGridLayout(self.from_input)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.password_text = QtWidgets.QLabel(self.from_input)
        self.password_text.setObjectName("password_text")
        self.gridLayout.addWidget(self.password_text, 1, 0, 1, 1)
        self.username_dedit = QtWidgets.QLineEdit(self.from_input)
        self.username_dedit.setObjectName("username_dedit")
        self.gridLayout.addWidget(self.username_dedit, 0, 1, 1, 1)
        self.username_text = QtWidgets.QLabel(self.from_input)
        self.username_text.setObjectName("username_text")
        self.gridLayout.addWidget(self.username_text, 0, 0, 1, 1)
        self.passwor_dedit = QtWidgets.QLineEdit(self.from_input)
        self.passwor_dedit.setObjectName("passwor_dedit")
        self.gridLayout.addWidget(self.passwor_dedit, 1, 1, 1, 1)
        self.loginbutton = QtWidgets.QToolButton(self.from_input)
        self.loginbutton.setObjectName("loginbutton")
        self.gridLayout.addWidget(self.loginbutton, 2, 0, 1, 1)
        self.remember_checkBox = QtWidgets.QCheckBox(self.from_input)
        self.remember_checkBox.setObjectName("remember_checkBox")
        self.gridLayout.addWidget(self.remember_checkBox, 2, 1, 1, 1)

        self.retranslateUi(auth_login)
        QtCore.QMetaObject.connectSlotsByName(auth_login)

    def retranslateUi(self, auth_login):
        _translate = QtCore.QCoreApplication.translate
        auth_login.setWindowTitle(_translate("auth_login", "Form"))
        self.password_text.setText(_translate("auth_login", "password"))
        self.username_text.setText(_translate("auth_login", "username:"))
        self.loginbutton.setText(_translate("auth_login", "登录"))
        self.remember_checkBox.setText(_translate("auth_login", "记住用户密码"))
