# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\jobs_pull.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_jobs_pull(object):
    def setupUi(self, jobs_pull):
        jobs_pull.setObjectName("jobs_pull")
        jobs_pull.resize(962, 622)
        jobs_pull.setMinimumSize(QtCore.QSize(962, 622))
        self.gridLayout_2 = QtWidgets.QGridLayout(jobs_pull)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(jobs_pull)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.updata_jobs_button = QtWidgets.QToolButton(self.frame)
        self.updata_jobs_button.setObjectName("updata_jobs_button")
        self.gridLayout.addWidget(self.updata_jobs_button, 0, 1, 1, 1)
        self.jobs_list = QtWidgets.QComboBox(self.frame)
        self.jobs_list.setObjectName("jobs_list")
        self.gridLayout.addWidget(self.jobs_list, 0, 0, 1, 1)
        self.images_list = QtWidgets.QComboBox(self.frame)
        self.images_list.setObjectName("images_list")
        self.gridLayout.addWidget(self.images_list, 0, 2, 1, 1)
        self.download_Button = QtWidgets.QToolButton(self.frame)
        self.download_Button.setObjectName("download_Button")
        self.gridLayout.addWidget(self.download_Button, 0, 3, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 0))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 4)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(jobs_pull)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.gridLayout_2.setRowMinimumHeight(0, 1)
        self.gridLayout_2.setRowMinimumHeight(1, 9)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 9)

        self.retranslateUi(jobs_pull)
        QtCore.QMetaObject.connectSlotsByName(jobs_pull)

    def retranslateUi(self, jobs_pull):
        _translate = QtCore.QCoreApplication.translate
        jobs_pull.setWindowTitle(_translate("jobs_pull", "Form"))
        self.updata_jobs_button.setText(_translate("jobs_pull", "updata jobs"))
        self.download_Button.setText(_translate("jobs_pull", "Download to local"))
        self.progressBar.setFormat(_translate("jobs_pull", "%p%"))
